"""Five-seed evaluation of the simulated study - SIMULATED data only.

Everything here describes a *simulator*. A model trained on these tables learns the
assumptions written in `src/config.py`; the scores below are not evidence about real food
waste or real digesters, and every artefact this module writes carries the SIMULATED marker.

The frozen protocol this implements is `docs/model_specification.md` §9:

* scenario-grouped 70/15/15 split, replicates staying with their scenario;
* preprocessing fit on the training split only (done in `src/train_models.py`);
* the test split is opened once, at the end, for every seed;
* metrics reported as **mean plus spread over the seeds** - descriptive, never inferential;
* the held-out family of §8 reported separately and never used for fitting;
* feature importance labelled "what the model used", never "what drives the biology";
* the pre-declared decision rules of §9.1 evaluated from the collected numbers.

Plotting uses the Agg backend so the module runs headless in CI and in the sandbox.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn
from matplotlib.figure import Figure
from sklearn.inspection import permutation_importance

from src import config
from src.simulate_data import simulate, simulate_ood
from src.train_models import (
    FittedModel,
    fit_all_models,
    make_feature_frame,
    predict_model,
    regression_metrics,
    split_frame,
    transform_features,
)

METRICS: tuple[str, ...] = ("r2", "mae", "rmse")
TREE_MODELS: tuple[str, ...] = ("random_forest", "hist_gradient_boosting")
EVALUATED_SPLITS: tuple[str, ...] = ("validation", "test")

# Pre-declared in SPEC_V1 §9.1 (F3): if Ridge reaches this fraction of the best tree's mean
# test R2, the model comparison is declared uninformative and no ranking is reported.
F3_THRESHOLD = 0.95
MIN_SCENARIOS = 10
IMPORTANCE_LABEL = (
    "what the model used (permutation importance on the test split) - "
    "not what drives the biology"
)
SCOPE_NOTE = (
    "Every number in this directory comes from synthetic data generated by src/simulate_data.py "
    f"({config.SIMULATOR_VERSION}). A model trained on these tables learns the simulator's "
    "assumptions; the scores are not evidence of accuracy on real food waste or real digesters, "
    "and no result here describes a physical plant."
)


def _check_names(names: tuple[str, ...]) -> None:
    unknown = [name for name in names if name not in config.MODEL_NAMES]
    if unknown:
        raise ValueError(
            f"unknown model(s) {unknown}; the five declared models are {config.MODEL_NAMES}"
        )


def evaluate_seed(
    seed: int,
    n_scenarios: int,
    *,
    ood_scenarios: int = 0,
    names: tuple[str, ...] = config.MODEL_NAMES,
) -> dict[str, Any]:
    """Fit the declared models for one seed and score them on validation, test and held-out rows.

    Returns the seed-level metric rows, the held-out rows, the fitted models and the splits -
    the fitted models and the held-out frame are kept so callers can draw figures and check
    that the held-out family was never part of fitting.
    """
    _check_names(names)
    if n_scenarios < MIN_SCENARIOS:
        raise ValueError(
            f"at least {MIN_SCENARIOS} scenarios are required for a grouped 70/15/15 split "
            f"(got {n_scenarios})"
        )
    if ood_scenarios < 0:
        raise ValueError(f"ood_scenarios must not be negative (got {ood_scenarios})")

    frame, _ = simulate(seed=seed, n_scenarios=n_scenarios)
    splits = split_frame(frame)
    fitted = fit_all_models(splits, seed, names=names)

    rows: list[dict[str, Any]] = []
    for split_name in EVALUATED_SPLITS:
        y_true = splits[split_name][config.TARGET].to_numpy(dtype=float)
        for name, model in fitted.items():
            rows.append(
                {
                    "seed": seed,
                    "model": name,
                    "split": split_name,
                    **regression_metrics(y_true, predict_model(model, splits[split_name])),
                }
            )

    ood = simulate_ood(seed=seed, n_scenarios=ood_scenarios) if ood_scenarios else None
    ood_rows: list[dict[str, Any]] = []
    if ood is not None:
        y_true = ood[config.TARGET].to_numpy(dtype=float)
        for name, model in fitted.items():
            ood_rows.append(
                {
                    "seed": seed,
                    "model": name,
                    "split": "ood",
                    **regression_metrics(y_true, predict_model(model, ood)),
                }
            )
        splits["ood"] = ood

    return {
        "seed": seed,
        "rows": rows,
        "ood_rows": ood_rows,
        "fitted": fitted,
        "splits": splits,
        "ood": ood,
    }


def summarise_seed_metrics(
    rows: list[dict[str, Any]], *, metrics: tuple[str, ...] = METRICS
) -> list[dict[str, Any]]:
    """Collapse seed-level rows into mean and spread. Descriptive, not inferential.

    `std` is `None` when fewer than two finite values exist for that cell: with one seed there
    is no spread to report, and reporting `0.0` would look like certainty.
    """
    if not rows:
        raise ValueError("no rows to summarise")
    unknown = [metric for metric in metrics if metric not in METRICS]
    if unknown:
        raise ValueError(f"unknown metric(s) {unknown}; the declared metrics are {METRICS}")

    grouped: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in rows:
        grouped.setdefault((row["model"], row["split"]), []).append(row)

    summary: list[dict[str, Any]] = []
    for (model, split), group in sorted(grouped.items()):
        for metric in metrics:
            # sorted so that the summary does not depend on row order (float addition is not
            # associative, and a summary that changes when the input is shuffled is a bug)
            values = sorted(
                float(row[metric])
                for row in group
                if row.get(metric) is not None and math.isfinite(float(row[metric]))
            )
            summary.append(
                {
                    "model": model,
                    "split": split,
                    "metric": metric,
                    "mean": float(np.mean(values)) if values else None,
                    "std": float(np.std(values, ddof=1)) if len(values) > 1 else None,
                    "minimum": min(values) if values else None,
                    "maximum": max(values) if values else None,
                    "n_seeds": len(group),
                    "n_finite": len(values),
                }
            )
    return summary


def evaluate_decision_rules(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Apply the pre-declared rules F3 and F7 to the collected test-split numbers."""
    test_rows = [row for row in rows if row["split"] == "test" and row.get("r2") is not None]
    if not test_rows:
        raise ValueError("the decision rules need at least one finite test-split R2 row")

    by_model: dict[str, list[float]] = {}
    for row in test_rows:
        by_model.setdefault(row["model"], []).append(float(row["r2"]))
    if "dummy" not in by_model:
        raise ValueError("the decision rules need the dummy baseline rows (model 'dummy')")

    dummy_range = (min(by_model["dummy"]), max(by_model["dummy"]))
    # sorted, then take the last: ties resolve to the alphabetically later model, deterministically
    best_model = sorted(
        (float(np.mean(values)), name) for name, values in by_model.items()
    )[-1][1]
    best_range = (min(by_model[best_model]), max(by_model[best_model]))
    ridge_mean = float(np.mean(by_model["ridge"])) if "ridge" in by_model else None

    trees = {name: values for name, values in by_model.items() if name in TREE_MODELS}
    if trees:
        tree_mean, tree_name = max(
            (float(np.mean(values)), name) for name, values in trees.items()
        )
        f3_fires = ridge_mean is not None and ridge_mean >= F3_THRESHOLD * tree_mean
        f3_verdict = (
            "uninformative - do not report a model ranking"
            if f3_fires
            else "informative - the nonlinear models earn their place"
        )
    else:
        tree_mean, tree_name = None, None
        f3_fires = False
        f3_verdict = "not evaluable - no tree model was run"

    # "mean +/- spread" is operationalised as the observed min-max range, which is the wider
    # (more conservative) reading: it fires the warning more readily than a +/- 1 std interval.
    f7_fires = best_range[0] <= dummy_range[1] and dummy_range[0] <= best_range[1]
    return {
        "f3_rule": (
            "if Ridge's mean test R2 reaches "
            f"{F3_THRESHOLD:.0%} of the best tree's mean test R2, the comparison is uninformative"
        ),
        "f3_threshold": F3_THRESHOLD,
        "f3_fires": f3_fires,
        "f3_verdict": f3_verdict,
        "f3_ridge_mean_r2": ridge_mean,
        "f3_best_tree": tree_name,
        "f3_best_tree_mean_r2": tree_mean,
        "f7_rule": (
            "if the best model's range of test R2 across seeds overlaps the dummy baseline's "
            "range, the apparent skill is reported as seed-dependent"
        ),
        "f7_fires": f7_fires,
        "f7_verdict": (
            "seed-dependent - report the overlap, do not claim skill"
            if f7_fires
            else "stable - the best model clears the baseline's spread"
        ),
        "f7_best_model": best_model,
        "f7_best_model_range": list(best_range),
        "f7_dummy_range": list(dummy_range),
        "n_test_rows": len(test_rows),
    }


def feature_importance_table(
    fitted: dict[str, FittedModel],
    frame: pd.DataFrame,
    *,
    seed: int = 0,
    n_repeats: int = 5,
) -> list[dict[str, Any]]:
    """Permutation importance per model, labelled as model usage rather than causation.

    Permutation is applied to the standardised feature matrix. Standardising is an affine map,
    so permuting a standardised column permutes the same rows as permuting the raw column does -
    the ordering of the importances is unaffected.
    """
    y_true = frame[config.TARGET].to_numpy(dtype=float)
    rows: list[dict[str, Any]] = []
    for name, model in fitted.items():
        x = transform_features(model.preprocessor, make_feature_frame(frame))
        result = permutation_importance(
            model.estimator, x, y_true, n_repeats=n_repeats, random_state=seed, scoring="r2"
        )
        # item access rather than attribute access: sklearn types this return as Bunch | dict
        means = np.asarray(result["importances_mean"], dtype=float)
        spreads = np.asarray(result["importances_std"], dtype=float)
        for index, feature in enumerate(config.FEATURES):
            rows.append(
                {
                    "model": name,
                    "feature": feature,
                    "importance_mean": float(means[index]),
                    "importance_std": float(spreads[index]),
                    "n_repeats": n_repeats,
                    "label": IMPORTANCE_LABEL,
                }
            )
    return rows


def _stamp(fig: Figure, title: str, note: str) -> None:
    """Put the SIMULATED marker and the provenance on every figure, not only in the filename."""
    fig.suptitle(f"[{config.SIMULATED_MARKER}] {title}", fontsize=12)
    fig.text(
        0.01,
        0.005,
        f"{note} | simulator {config.SIMULATOR_VERSION} | provenance {config.DATA_PROVENANCE} "
        f"| {config.AS_OF}",
        fontsize=7,
        color="0.35",
    )


def _panel_axes(model_count: int, height: float = 3.4) -> tuple[Figure, Any]:
    figure, axes = plt.subplots(1, model_count, figsize=(3.2 * model_count, height), squeeze=False)
    return figure, axes[0]


def build_prediction_figure(
    fitted: dict[str, FittedModel], frame: pd.DataFrame, *, title: str
) -> Figure:
    """True vs predicted on one split, one panel per model."""
    y_true = frame[config.TARGET].to_numpy(dtype=float)
    fig, axes = _panel_axes(len(fitted))
    for ax, (name, model) in zip(axes, fitted.items(), strict=True):
        y_pred = predict_model(model, frame)
        ax.scatter(y_true, y_pred, s=8, alpha=0.5, edgecolors="none")
        low = float(min(y_true.min(), y_pred.min()))
        high = float(max(y_true.max(), y_pred.max()))
        ax.plot([low, high], [low, high], color="0.35", lw=1, ls="--")
        r2 = regression_metrics(y_true, y_pred)["r2"]
        ax.set_title(f"{name}\nR2={r2:.3f}" if r2 is not None else f"{name}\nR2 undefined")
        ax.set_xlabel("true (simulated)")
        ax.set_ylabel("predicted")
    _stamp(fig, title, "true vs predicted on the test split")
    fig.tight_layout(rect=(0.0, 0.03, 1.0, 0.92))
    return fig


def build_residual_figure(
    fitted: dict[str, FittedModel], frame: pd.DataFrame, *, title: str
) -> Figure:
    """Residual vs predicted on one split, one panel per model."""
    y_true = frame[config.TARGET].to_numpy(dtype=float)
    fig, axes = _panel_axes(len(fitted))
    for ax, (name, model) in zip(axes, fitted.items(), strict=True):
        y_pred = predict_model(model, frame)
        ax.scatter(y_pred, y_true - y_pred, s=8, alpha=0.5, edgecolors="none")
        ax.axhline(0.0, color="0.35", lw=1, ls="--")
        ax.set_title(name)
        ax.set_xlabel("predicted")
        ax.set_ylabel("residual (true - predicted)")
    _stamp(fig, title, "residuals on the test split")
    fig.tight_layout(rect=(0.0, 0.03, 1.0, 0.92))
    return fig


def build_seed_spread_figure(rows: list[dict[str, Any]], *, title: str) -> Figure:
    """Per-seed test R2 by model, with the dummy baseline's own range shaded."""
    test_rows = [row for row in rows if row["split"] == "test" and row.get("r2") is not None]
    if not test_rows:
        raise ValueError("the seed-spread figure needs at least one finite test-split R2 row")
    models = sorted({row["model"] for row in test_rows})

    fig, ax = plt.subplots(figsize=(6.6, 3.8))
    if "dummy" in models:
        dummy = [float(row["r2"]) for row in test_rows if row["model"] == "dummy"]
        ax.axhspan(min(dummy), max(dummy), color="0.88", zorder=0)
    for position, name in enumerate(models):
        values = [float(row["r2"]) for row in test_rows if row["model"] == name]
        ax.scatter([position] * len(values), values, s=22, alpha=0.85, zorder=2)
        ax.plot(
            [position - 0.22, position + 0.22],
            [float(np.mean(values))] * 2,
            color="0.15",
            lw=2.0,
            zorder=3,
        )
    ax.set_xticks(range(len(models)), models, rotation=12)
    ax.set_ylabel("test R2 (one point per seed)")
    _stamp(fig, title, "spread across seeds; shaded band = dummy baseline range")
    fig.tight_layout(rect=(0.0, 0.04, 1.0, 0.92))
    return fig


def build_importance_figure(table: list[dict[str, Any]], *, title: str) -> Figure:
    """Permutation importance per model - explicitly 'what the model used'."""
    models = sorted({row["model"] for row in table})
    fig, axes = _panel_axes(len(models), height=3.6)
    for ax, name in zip(axes, models, strict=True):
        rows = [row for row in table if row["model"] == name]
        order = sorted(range(len(rows)), key=lambda index: rows[index]["importance_mean"])
        ax.barh(
            [rows[index]["feature"] for index in order],
            [rows[index]["importance_mean"] for index in order],
            color="0.45",
        )
        ax.axvline(0.0, color="0.2", lw=0.8)
        ax.set_title(name)
        ax.tick_params(axis="y", labelsize=7)
    _stamp(fig, title, "permutation importance (R2 drop) - model usage, not biology")
    fig.tight_layout(rect=(0.0, 0.03, 1.0, 0.92))
    return fig


def save_figure(fig: Figure, path: Path | str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=140)
    plt.close(fig)
    return path


def _write_csv(frame: pd.DataFrame, path: Path) -> Path:
    """Write a CSV with the SIMULATED marker on every row, not only in the file name."""
    frame = frame.copy()
    frame["simulated"] = config.SIMULATED_MARKER
    frame["simulator_version"] = config.SIMULATOR_VERSION
    frame.to_csv(path, index=False)
    return path


def _write_json(payload: dict[str, Any], path: Path) -> Path:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _run_metadata(result: dict[str, Any]) -> dict[str, Any]:
    return {
        "simulated": True,
        "data_provenance": config.DATA_PROVENANCE,
        "simulator_version": config.SIMULATOR_VERSION,
        "as_of": config.AS_OF,
        "seeds": list(result["seeds"]),
        "n_scenarios": result["n_scenarios"],
        "ood_scenarios": result["ood_scenarios"],
        "models": list(result["models"]),
        "figure_seed": result["figure_seed"],
        "n_seed_rows": len(result["rows"]),
        "n_ood_rows": len(result["ood_rows"]),
        "split_rows": {name: len(part) for name, part in result["splits"].items()},
        "package_versions": {
            "numpy": np.__version__,
            "pandas": pd.__version__,
            "scikit-learn": sklearn.__version__,
        },
        "scope_note": SCOPE_NOTE,
    }


def write_results(result: dict[str, Any], outdir: Path | str) -> dict[str, Path]:
    """Write the metric tables, the decision rules, the metadata and the figures."""
    outdir = Path(outdir)
    figures_dir = outdir / "figures"
    outdir.mkdir(parents=True, exist_ok=True)

    paths = {
        "seed_level": _write_csv(pd.DataFrame(result["rows"]), outdir / "metrics_seed_level.csv"),
        "summary": _write_csv(pd.DataFrame(result["summary"]), outdir / "metrics_summary.csv"),
        "ood": _write_csv(pd.DataFrame(result["ood_rows"]), outdir / "metrics_ood.csv"),
        "feature_importance": _write_csv(
            pd.DataFrame(result["feature_importance"]), outdir / "feature_importance.csv"
        ),
        # provenance travels with the rules file too: a bare JSON of thresholds and booleans is
        # exactly the kind of artefact that gets quoted out of context later
        "rules": _write_json(
            {
                **result["rules"],
                "simulated": True,
                "data_provenance": config.DATA_PROVENANCE,
                "simulator_version": config.SIMULATOR_VERSION,
                "as_of": config.AS_OF,
            },
            outdir / "decision_rules.json",
        ),
        "metadata": _write_json(_run_metadata(result), outdir / "run_metadata.json"),
    }

    # Figures describe one seed's fitted models; the metrics CSVs cover every seed.
    test_frame = result["splits"]["test"]
    paths["figures/predicted_vs_true"] = save_figure(
        build_prediction_figure(
            result["fitted"], test_frame, title=f"predicted vs true (seed {result['figure_seed']})"
        ),
        figures_dir / "predicted_vs_true.png",
    )
    paths["figures/residuals_vs_predicted"] = save_figure(
        build_residual_figure(
            result["fitted"], test_frame, title=f"residuals (seed {result['figure_seed']})"
        ),
        figures_dir / "residuals_vs_predicted.png",
    )
    paths["figures/seed_spread"] = save_figure(
        build_seed_spread_figure(result["rows"], title="test R2 across seeds"),
        figures_dir / "seed_spread.png",
    )
    paths["figures/feature_importance"] = save_figure(
        build_importance_figure(result["feature_importance"], title="what each model used"),
        figures_dir / "feature_importance.png",
    )
    return paths


def evaluate_models(
    seeds: tuple[int, ...] = config.SEEDS,
    n_scenarios: int = config.N_SCENARIOS,
    *,
    ood_scenarios: int = config.N_OOD_SCENARIOS,
    names: tuple[str, ...] | None = None,
) -> dict[str, Any]:
    """Run the frozen protocol over several seeds and collect every number the rules need."""
    chosen = tuple(config.MODEL_NAMES if names is None else names)
    seed_list = tuple(int(seed) for seed in seeds)
    if not seed_list:
        raise ValueError("at least one seed is required")
    _check_names(chosen)

    rows: list[dict[str, Any]] = []
    ood_rows: list[dict[str, Any]] = []
    fitted: dict[str, FittedModel] = {}
    splits: dict[str, pd.DataFrame] = {}
    for index, seed in enumerate(seed_list):
        outcome = evaluate_seed(
            seed, n_scenarios, ood_scenarios=ood_scenarios, names=chosen
        )
        rows.extend(outcome["rows"])
        ood_rows.extend(outcome["ood_rows"])
        if index == 0:
            # figures and the importance table describe the first seed; the CSVs cover all seeds
            fitted = outcome["fitted"]
            splits = outcome["splits"]

    return {
        "seeds": list(seed_list),
        "n_scenarios": n_scenarios,
        "ood_scenarios": ood_scenarios,
        "models": list(chosen),
        "figure_seed": seed_list[0],
        "rows": rows,
        "ood_rows": ood_rows,
        "summary": summarise_seed_metrics(rows),
        "rules": evaluate_decision_rules(rows),
        "feature_importance": feature_importance_table(
            fitted, splits["test"], seed=seed_list[0], n_repeats=5
        ),
        "fitted": fitted,
        "splits": splits,
    }


def _parse_seeds(text: str) -> tuple[int, ...]:
    try:
        seeds = tuple(int(part.strip()) for part in text.split(",") if part.strip())
    except ValueError as exc:
        raise ValueError(f"could not read the seed list {text!r}: {exc}") from exc
    if not seeds:
        raise ValueError("at least one seed is required")
    return seeds


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run the frozen 5-seed evaluation on SIMULATED data (SPEC_V1)."
    )
    parser.add_argument("--seeds", default=",".join(str(seed) for seed in config.SEEDS))
    parser.add_argument("--n-scenarios", type=int, default=config.N_SCENARIOS)
    parser.add_argument("--ood-scenarios", type=int, default=config.N_OOD_SCENARIOS)
    parser.add_argument(
        "--models", default="", help="comma-separated subset of the five declared models"
    )
    parser.add_argument("--outdir", default=str(config.RESULTS_DIR))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    seeds = _parse_seeds(args.seeds)
    names = (
        tuple(part.strip() for part in args.models.split(",") if part.strip())
        if args.models
        else config.MODEL_NAMES
    )
    _check_names(names)

    result = evaluate_models(
        seeds=seeds,
        n_scenarios=args.n_scenarios,
        ood_scenarios=args.ood_scenarios,
        names=names,
    )
    paths = write_results(result, args.outdir)

    for row in result["rows"]:
        if row["split"] != "test":
            continue
        r2 = "undefined" if row["r2"] is None else f"{row['r2']:+.4f}"
        print(
            f"seed {row['seed']} {row['model']}: test R2={r2} "
            f"MAE={row['mae']:.2f} RMSE={row['rmse']:.2f} [SIMULATED]"
        )
    for row in result["summary"]:
        if row["split"] != "test":
            continue
        mean = "n/a" if row["mean"] is None else f"{row['mean']:+.4f}"
        spread = "n/a" if row["std"] is None else f"{row['std']:.4f}"
        print(
            f"{row['model']} test {row['metric']}: mean {mean} +/- {spread} "
            f"over {row['n_finite']}/{row['n_seeds']} seeds [SIMULATED]"
        )
    print(
        f"F3: {result['rules']['f3_verdict']} | F7: {result['rules']['f7_verdict']} [SIMULATED]"
    )
    print(f"wrote {len(paths)} artefacts to {Path(args.outdir)} [SIMULATED]")
    return 0


if __name__ == "__main__":  # pragma: no cover - module entry point
    raise SystemExit(main())
